# Generated by Django 3.1.4 on 2020-12-15 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='User')),
                ('type', models.CharField(choices=[('user', 'User'), ('ambulanceHub', 'Ambulance Hub'), ('ambulance', 'Ambulance')], default='user', max_length=20, verbose_name='Account Type')),
            ],
        ),
        migrations.RenameModel(
            old_name='Ambulance_hub',
            new_name='AmbulanceHub',
        ),
    ]
