# Generated by Django 3.1.4 on 2020-12-24 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='purpose',
            field=models.CharField(choices=[('user_activation', 'User Activation'), ('hub_activation', 'Hub Activation'), ('password_reset', 'Password Reset')], max_length=30, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
