# Generated by Django 3.1.4 on 2020-12-24 15:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201224_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancehub',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
    ]
